param(
    [Parameter(Mandatory = $true)]
    [string]$MainServerUrl,

    [string]$ApiKey = "",
    [string]$AuthToken = "",
    [string]$RefreshToken = "",
    [string]$Username = "",
    [string]$Password = "",
    [string]$PythonPath = "python",

    [switch]$DisableRemoteImports,
    [switch]$DisablePetex,
    [switch]$DisableSslVerify,
    [switch]$ReinstallService
)

$ErrorActionPreference = "Stop"

function Test-IsAdmin {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)
}

function Wait-AgentReady {
    param(
        [int]$TimeoutSeconds = 60
    )

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    while ((Get-Date) -lt $deadline) {
        try {
            $resp = Invoke-WebRequest -Uri "http://127.0.0.1:9000/variables/" -UseBasicParsing -TimeoutSec 3
            if ($resp.StatusCode -eq 200) {
                return $true
            }
        }
        catch {
            Start-Sleep -Seconds 1
        }
    }

    return $false
}

if (-not (Test-IsAdmin)) {
    throw "Run this script in an Administrator PowerShell window."
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location -LiteralPath $scriptDir

if (-not (Test-Path -LiteralPath ".\\windows_service.py")) {
    throw "windows_service.py not found. Run from workflow-agent directory."
}

if (-not (Test-Path -LiteralPath ".\\requirements.txt")) {
    throw "requirements.txt not found. Run from workflow-agent directory."
}

if (-not (Test-Path -LiteralPath ".\\.venv\\Scripts\\python.exe")) {
    Write-Host "[1/6] Creating virtual environment..."
    & $PythonPath -m venv .venv
}

$venvPython = (Resolve-Path ".\\.venv\\Scripts\\python.exe").Path

Write-Host "[2/6] Installing dependencies..."
& $venvPython -m pip install --upgrade pip
& $venvPython -m pip install -r requirements.txt

Write-Host "[3/6] Writing service.env..."
$sslVerifyValue = if ($DisableSslVerify) { "0" } else { "1" }
$disableRemoteImportsValue = if ($DisableRemoteImports) { "1" } else { "0" }
$disablePetexValue = if ($DisablePetex) { "1" } else { "0" }

$envLines = @(
    "# Generated by install_service.ps1",
    "WORKFLOW_AGENT_MAIN_SERVER_URL=$MainServerUrl",
    "WORKFLOW_AGENT_SSL_VERIFY=$sslVerifyValue",
    "WORKFLOW_AGENT_DISABLE_REMOTE_IMPORTS=$disableRemoteImportsValue",
    "WORKFLOW_AGENT_DISABLE_PETEX=$disablePetexValue"
)

if ($ApiKey) { $envLines += "WORKFLOW_AGENT_API_KEY=$ApiKey" }
if ($AuthToken) { $envLines += "WORKFLOW_AGENT_AUTH_TOKEN=$AuthToken" }
if ($RefreshToken) { $envLines += "WORKFLOW_AGENT_REFRESH_TOKEN=$RefreshToken" }
if ($Username) { $envLines += "WORKFLOW_AGENT_USERNAME=$Username" }
if ($Password) { $envLines += "WORKFLOW_AGENT_PASSWORD=$Password" }

$envLines | Set-Content -LiteralPath ".\\service.env" -Encoding UTF8

Write-Host "[4/6] Installing or updating Windows service..."
$serviceExists = $false
try {
    $query = & sc.exe query WorkflowAgentService 2>$null | Out-String
    if ($query -match "SERVICE_NAME:\s+WorkflowAgentService") {
        $serviceExists = $true
    }
}
catch {
    $serviceExists = $false
}

if ($serviceExists -and $ReinstallService) {
    try { & $venvPython .\\windows_service.py stop } catch {}
    & $venvPython .\\windows_service.py remove
    $serviceExists = $false
}

if (-not $serviceExists) {
    & $venvPython .\\windows_service.py --startup auto install
}

Write-Host "[5/6] Restarting service..."
try { & $venvPython .\\windows_service.py stop } catch {}
try { & $venvPython .\\windows_service.py start } catch { & $venvPython .\\windows_service.py start }

Write-Host "[6/6] Health check..."
if (Wait-AgentReady -TimeoutSeconds 90) {
    Write-Host "WorkflowAgentService is running at http://127.0.0.1:9000"
}
else {
    Write-Warning "Service started but health check failed. Check logs/service_stderr.log"
}

Write-Host "Done."
