param(
    [string]$Version = "1.0.0",
    [string]$MainServerUrl = "https://btlweb/api",

    [string]$ApiKey = "",
    [string]$AuthToken = "",
    [string]$RefreshToken = "",
    [string]$Username = "",
    [string]$Password = "",

    [switch]$DisableRemoteImports,
    [switch]$DisablePetex,
    [switch]$DisableSslVerify,

    [ValidateSet("PyInstaller", "Nuitka")]
    [string]$BuildTool = "PyInstaller",

    [string]$WinSWUrl = "https://github.com/winsw/winsw/releases/latest/download/WinSW-x64.exe"
)

$ErrorActionPreference = "Stop"

function Escape-Xml {
    param([string]$Value)
    if ($null -eq $Value) { return "" }
    return [System.Security.SecurityElement]::Escape($Value)
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptDir
Set-Location -LiteralPath $repoRoot

if (-not (Test-Path -LiteralPath ".\\build_release.ps1")) {
    throw "build_release.ps1 is missing in repo root."
}

$versionPattern = '^\d+\.\d+\.\d+$'
if ($Version -notmatch $versionPattern) {
    throw "Version must use MSI format: major.minor.build (example: 1.0.0)."
}

Write-Host "[1/5] Building runner binary..."
& powershell -ExecutionPolicy Bypass -File .\\build_release.ps1 -BuildTool $BuildTool

$runnerPath = Resolve-Path .\\dist\\release\\WorkflowAgentRunner.exe

$stageDir = Join-Path $repoRoot "dist\\msi_stage"
$outDir = Join-Path $repoRoot "dist\\msi"
New-Item -ItemType Directory -Path $stageDir -Force | Out-Null
New-Item -ItemType Directory -Path $outDir -Force | Out-Null

Write-Host "[2/5] Preparing service wrapper files..."
Copy-Item -LiteralPath $runnerPath -Destination (Join-Path $stageDir "WorkflowAgentRunner.exe") -Force

Invoke-WebRequest -Uri $WinSWUrl -OutFile (Join-Path $stageDir "WorkflowAgentService.exe")

$sslVerifyValue = if ($DisableSslVerify) { "0" } else { "1" }
$disableRemoteImportsValue = if ($DisableRemoteImports) { "1" } else { "0" }
$disablePetexValue = if ($DisablePetex) { "1" } else { "0" }

$xml = @"
<service>
  <id>WorkflowAgentService</id>
  <name>Workflow Agent Service</name>
  <description>Runs Workflow Agent workflows locally.</description>
  <executable>%BASE%\\WorkflowAgentRunner.exe</executable>
  <workingdirectory>%BASE%</workingdirectory>
  <stoptimeout>15 sec</stoptimeout>
  <onfailure action="restart" delay="10 sec"/>
  <onfailure action="restart" delay="30 sec"/>
  <log mode="roll-by-size-time">
    <sizeThreshold>10240</sizeThreshold>
    <keepFiles>10</keepFiles>
  </log>
  <env name="WORKFLOW_AGENT_MAIN_SERVER_URL" value="$(Escape-Xml $MainServerUrl)"/>
  <env name="WORKFLOW_AGENT_SSL_VERIFY" value="$sslVerifyValue"/>
  <env name="WORKFLOW_AGENT_DISABLE_REMOTE_IMPORTS" value="$disableRemoteImportsValue"/>
  <env name="WORKFLOW_AGENT_DISABLE_PETEX" value="$disablePetexValue"/>
"@

if ($ApiKey) { $xml += "`n  <env name=`"WORKFLOW_AGENT_API_KEY`" value=`"$(Escape-Xml $ApiKey)`"/>" }
if ($AuthToken) { $xml += "`n  <env name=`"WORKFLOW_AGENT_AUTH_TOKEN`" value=`"$(Escape-Xml $AuthToken)`"/>" }
if ($RefreshToken) { $xml += "`n  <env name=`"WORKFLOW_AGENT_REFRESH_TOKEN`" value=`"$(Escape-Xml $RefreshToken)`"/>" }
if ($Username) { $xml += "`n  <env name=`"WORKFLOW_AGENT_USERNAME`" value=`"$(Escape-Xml $Username)`"/>" }
if ($Password) { $xml += "`n  <env name=`"WORKFLOW_AGENT_PASSWORD`" value=`"$(Escape-Xml $Password)`"/>" }

$xml += "`n</service>`n"
$xml | Set-Content -LiteralPath (Join-Path $stageDir "WorkflowAgentService.xml") -Encoding UTF8

$envFile = @(
    "# Generated by installer/build_msi.ps1",
    "WORKFLOW_AGENT_MAIN_SERVER_URL=$MainServerUrl",
    "WORKFLOW_AGENT_SSL_VERIFY=$sslVerifyValue",
    "WORKFLOW_AGENT_DISABLE_REMOTE_IMPORTS=$disableRemoteImportsValue",
    "WORKFLOW_AGENT_DISABLE_PETEX=$disablePetexValue"
)
if ($ApiKey) { $envFile += "WORKFLOW_AGENT_API_KEY=$ApiKey" }
if ($AuthToken) { $envFile += "WORKFLOW_AGENT_AUTH_TOKEN=$AuthToken" }
if ($RefreshToken) { $envFile += "WORKFLOW_AGENT_REFRESH_TOKEN=$RefreshToken" }
if ($Username) { $envFile += "WORKFLOW_AGENT_USERNAME=$Username" }
if ($Password) { $envFile += "WORKFLOW_AGENT_PASSWORD=$Password" }
$envFile | Set-Content -LiteralPath (Join-Path $stageDir "service.env") -Encoding UTF8

Write-Host "[3/5] Checking WiX toolset..."
$wixCmd = Get-Command wix -ErrorAction SilentlyContinue
if (-not $wixCmd) {
    throw "WiX v4 CLI not found. Install with: dotnet tool install --global wix"
}

$wxsPath = Resolve-Path .\\installer\\WorkflowAgent.wxs
$outMsi = Join-Path $outDir ("WorkflowAgent-" + $Version + ".msi")

Write-Host "[4/5] Building MSI..."
& $wixCmd.Source build $wxsPath -dSourceDir=$stageDir -dProductVersion=$Version -o $outMsi

if (-not (Test-Path -LiteralPath $outMsi)) {
    throw "MSI build failed: output not found ($outMsi)."
}

Write-Host "[5/5] Done"
Write-Host "MSI output: $outMsi"

